### ISSUE TITLE
absolute path including drive letter for windows download_path

### ISSUE THREAD

**Issue by dts350z** [OrfiTeam/OrpheusDL#19]
What is the correct syntax for a download_path like:

D:\Me\Downloads\RS\RedSea\downloads

On windows when OrpheusDL is installed under C:?

I get: ValueError: path is on mount 'D:', start on mount 'C:'

**Comment by Dniel97** [comment]
@dts350z If I remember correctly D:/Me/Downloads/RS/RedSea/downloads should work fine or D:\\Me\\Downloads\\RS\\RedSea\\downloads. 

PS. That's is an OrpheusDL issue not a RedSea issue

**Comment by dts350z** [comment]
Yes I was just trying to re-use my Redsea location for Orpheusdl. 

Neither of those formats work. also D:\\Me\\Downloads\\RS\\RedSea\\downloads\\ does not work.

For "download_path": "D:/Glenn/Downloads/RS/RedSea/downloads/"

Traceback (most recent call last):
  File "C:\Users\Me.MYPC\orpheusdl\orpheus.py", line 223, in <module>
    main()
  File "C:\Users\Me.MYPC\orpheusdl\orpheus.py", line 218, in main
    orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
  File "C:\Users\Me.MYPC\orpheusdl\orpheus\core.py", line 389, in orpheus_core_download
    downloader.download_album(media_id, extra_kwargs=media.extra_kwargs)
  File "C:\Users\Me.MYPC\orpheusdl\orpheus\music_downloader.py", line 146, in download_album
    album_path = self._create_album_location(path, album_id, album_info)
  File "C:\Users\Me.MYPC\orpheusdl\orpheus\music_downloader.py", line 117, in _create_album_location
    album_path = fix_file_limit(album_path) + '/'
  File "C:\Users\Me.MYPC\orpheusdl\utils\utils.py", line 27, in fix_file_limit
    rel_path = os.path.relpath(path).replace('\\', '/')
  File "C:\Users\Me.MYPC\Anaconda3\envs\OrpheusDL\lib\ntpath.py", line 703, in relpath
    raise ValueError("path is on mount %r, start on mount %r" % (
ValueError: path is on mount 'D:', start on mount 'C:'

Seems like its choking on the drive letter not being C: where OrpheusDL is installed.

**Comment by Dniel97** [comment]
Have you tried:
```
D:\\Me\\Downloads\\RS\\RedSea\\downloads.
```

**Comment by dts350z** [comment]
with:
"download_path": "D:\\Me\\Downloads\\RS\\RedSea\\downloads.",

The error message appears to be the same, ends with:

ValueError: path is on mount 'D:', start on mount 'C:'

**Comment by Dniel97** [comment]
Fixed by #21.
