### ISSUE TITLE
Help lmao

### ISSUE THREAD

**Issue by okay-bullo** [OrfiTeam/OrpheusDL#39]
This is the error message I get

```
Traceback (most recent call last):
  File "C:\Users\EEE\documents\orpheusdl\orpheus.py", line 224, in <module>
    main()
  File "C:\Users\EEE\documents\orpheusdl\orpheus.py", line 37, in main
    orpheus = Orpheus(args.private)
  File "C:\Users\EEE\documents\orpheusdl\orpheus\core.py", line 108, in __init__
    self.settings = json.loads(open(self.settings_location, 'r').read()) if os.path.exists(self.settings_location) else {}
  File "C:\Users\EEE\AppData\Local\Programs\Python\Python39\lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "C:\Users\EEE\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "C:\Users\EEE\AppData\Local\Programs\Python\Python39\lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
json.decoder.JSONDecodeError: Invalid control character at: line 40 column 42 (char 1261)
```

**Comment by okay-bullo** [comment]
nvm there was a weird character in config.json mb.
