### ISSUE TITLE
Any idea how to resolve this ?

### ISSUE THREAD

**Issue by Wizflix** [OrfiTeam/OrpheusDL#44]
So I installed OrpheusDl and the Deezer module and everything went smoothly. I entered my credentials in the seetings.json. But then I tried downloading a playlist from Deezer and this showed on the console. Now everytime i want enter a track, album, playlist or even just trying "python orpheus.py" leads me to this error. Thanks for helping !

Traceback (most recent call last):
  File "C:\Users\malor\OrpheusDL\orpheus.py", line 224, in <module>
    main()
  File "C:\Users\malor\OrpheusDL\orpheus.py", line 37, in main
    orpheus = Orpheus(args.private)
              ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\malor\OrpheusDL\orpheus\core.py", line 108, in __init__
    self.settings = json.loads(open(self.settings_location, 'r').read()) if os.path.exists(self.settings_location) else {}
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\malor\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\malor\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\malor\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Invalid \escape: line 4 column 32 (char 70)

**Comment by OrfiDev** [comment]
@Wizflix it means you messed up your config file, ask ChatGPT how to fix it
