### ISSUE TITLE
raise TidalAuthError("TIDAL BOT protection, try again later!") modules.tidal.tidal_api.TidalAuthError: TIDAL BOT protection, try again later!

### ISSUE THREAD

**Issue by sultanmonsur** [OrfiTeam/OrpheusDL#45]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/orpheusdl/orpheus.py", line 224, in <module>
    main()
  File "/data/data/com.termux/files/home/orpheusdl/orpheus.py", line 219, in main
    orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
  File "/data/data/com.termux/files/home/orpheusdl/orpheus/core.py", line 368, in orpheus_core_download
    music = orpheus_session.load_module(mainmodule)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/orpheusdl/orpheus/core.py", line 210, in load_module
    loaded_module = class_(module_controller)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/data/data/com.termux/files/home/orpheusdl/modules/tidal/interface.py", line 114, in __init__
    sessions[session_type].auth(username, password)
  File "/data/data/com.termux/files/home/orpheusdl/modules/tidal/tidal_api.py", line 354, in auth
    raise TidalAuthError("TIDAL BOT protection, try again later!")
modules.tidal.tidal_api.TidalAuthError: TIDAL BOT protection, try again later!

**Comment by AJRXv2** [comment]
did you find any solution?

**Comment by Dniel97** [comment]
Update the tidal module and try again :)
