### ISSUE TITLE
Error downloading 360RA

### ISSUE THREAD

**Issue by AJRXv2** [OrfiTeam/OrpheusDL#49]
Any fix to this?

Traceback (most recent call last):
  File "C:\Users\narxerino\OrpheusDL\orpheus.py", line 224, in <module>
    main()
  File "C:\Users\narxerino\OrpheusDL\orpheus.py", line 219, in main
    orpheus_core_download(orpheus, media_to_download, tpm, sdm, path)
  File "C:\Users\narxerino\OrpheusDL\orpheus\core.py", line 368, in orpheus_core_download
    music = orpheus_session.load_module(mainmodule)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\narxerino\OrpheusDL\orpheus\core.py", line 210, in load_module
    loaded_module = class_(module_controller)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\narxerino\OrpheusDL\modules\tidal\interface.py", line 114, in __init__
    sessions[session_type].auth(username, password)
  File "C:\Users\narxerino\OrpheusDL\modules\tidal\tidal_api.py", line 354, in auth
    raise TidalAuthError("TIDAL BOT protection, try again later!")
modules.tidal.tidal_api.TidalAuthError: TIDAL BOT protection, try again later!

**Comment by Dniel97** [comment]
Your IP address got detected as a Bot, change your IP or use a VPN. Make sure to update the TIDAL module to the latest version.

**Comment by AJRXv2** [comment]
> Your IP address got detected as a Bot, change your IP or use a VPN. Make sure to update the TIDAL module to the latest version.

Thanks, I'll try it
